server.port=8082
spring.web.resources.static-locations=/upload/

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://mysql-server:3306/smarttt_new?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=root
spring.datasource.password=@Dwl1234567890
mybatis-plus.configuration.log-impl = org.apache.ibatis.logging.stdout.StdOutImpl
file.upload-dir=/home/smarttt_file

mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis-plus.mapper-locations=classpath*:/com/example/smartttcourse/mapper/**/*.xml

# minio
minio.url = http://minio-server:9000
minio.accessKey = minioadmin
minio.secretKey = @Dwl1234567890