version: '3.8'

networks:
  mynetwork:

services:

  smarttt-admin:
    build: ./smarttt-admin
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  smarttt-course:
    build: ./smarttt-course
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  smarttt-evaluation:
    build: ./smarttt-evaluation
    ports:
      - "8083:8083"
    networks:
      - mynetwork
